[package]
name = "beejlander"
version = "0.1.0"
authors = ["Gavin Markee <gavinmarkee@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.5.0"
regex = "1.3.7"
surf = "2.0.0-alpha.2"
